name: Build image and push into registry

on: workflow_call:
    secrets:
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
        fetch-depth: 0
    - uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
      continue-on-error: true
    - name: Build and push docker image # TODO: maybe just use docker action?
      run: |
        export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        export HEAD_COMMIT=$(git rev-parse --short HEAD)
        export IMAGE_VERSION="${BRANCH_NAME}-${HEAD_COMMIT}"
        printf "%s" "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin cr.yandex
        docker build -t cr.yandex/crp1of6bddata8ain3q5/text-to-speech:${IMAGE_VERSION} .
        docker push cr.yandex/crp1of6bddata8ain3q5/text-to-speech:${IMAGE_VERSION}
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_registry_password }}
        DOCKER_USERNAME: ${{ secrets.docker_registry_username }}
