name: Build image and push into registry

on:
  workflow_call:
    secrets:
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true
    inputs:
      service:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
        fetch-depth: 0
    - uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
      continue-on-error: true
    - name: Build and push docker image
      run: |
        mkdir -p ${HOME}/.local/bin
        export PATH=${HOME}/.local/bin:${PATH}
        curl -fsSLo skaffold "https://storage.googleapis.com/skaffold/releases/v1.24.1/skaffold-$(uname | tr '[:upper:]' '[:lower:]')-amd64"
        chmod +x skaffold && mv skaffold "${HOME}/.local/bin"
        skaffold config set --global collect-metrics false
        printf "%s" "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin cr.yandex
        cd $WORKDIR
        export LATEST_TAG=$(git tag -l "${TAG_PREFIX}*" --sort committerdate | tail -n 1 | sed -e "s/${TAG_PREFIX}//")
        export CURRENT_COMMIT=$(git rev-parse --short HEAD)
        export FINAL_TAG="${LATEST_TAG}-${CURRENT_COMMIT}"
        git tag $(echo $LATEST_TAG | )
        skaffold build --file-output=$HOME/tags.json
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_registry_password }}
        DOCKER_USERNAME: ${{ secrets.docker_registry_username }}
        WORKDIR: ${{ inputs.service }}
        TAG_PREFIX: "${{ inputs.service }}-"
