name: Build image and push into registry

on:
  workflow_call:
    secrets:
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true
    inputs:
      repository:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
        fetch-depth: 0
    - uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
      continue-on-error: true
    - name: Build and push docker image
      run: |
        printf "%s" "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin cr.yandex
        docker build -t ${{ github.event.inputs.repository }}:$(git describe --tags --always) .
        docker push ${{ github.event.inputs.repository }}:$(git describe --tags --always)
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_registry_password }}
        DOCKER_USERNAME: ${{ secrets.docker_registry_username }}
