name: Build image and push into registry

on:
  workflow_call:
    secrets:
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true
    inputs:
      service:
        required: false
        type: string
        default: .

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
        fetch-depth: 0
    - uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
      continue-on-error: true
    - uses: actions/cache@v2
      with:
        path: ~/.skaffold/
        key: sk-${{ github.sha }}
        restore-keys: |
          sk-${{ github.sha }}
          sk-
    - name: Build and push docker image
      run: |
        mkdir -p ${HOME}/.local/bin
        export PATH=${HOME}/.local/bin:${PATH}
        curl -fsSLo skaffold "https://storage.googleapis.com/skaffold/releases/v1.24.1/skaffold-$(uname | tr '[:upper:]' '[:lower:]')-amd64"
        chmod +x skaffold && mv skaffold "${HOME}/.local/bin"
        skaffold config set --global collect-metrics false
        printf "%s" "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin cr.yandex

        cat ~/.skaffold/cache || true

        if [ ${WORKDIR} = "." ]; then
          # simple case
          skaffold build --file-output=$HOME/tags.json
        else
          # handling monorepo here
          export TAG=$(git describe --tag --always --match "${TAG_PREFIX}*" | sed -e "s/${TAG_PREFIX}//")
          skaffold build --file-output=$HOME/tags.json --tag $TAG -f ${WORKDIR}/skaffold.yaml
        fi
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_registry_password }}
        DOCKER_USERNAME: ${{ secrets.docker_registry_username }}
        WORKDIR: ${{ inputs.service }}
        TAG_PREFIX: "${{ inputs.service }}-"
