name: Check frontend

on:
  workflow_call:

jobs:
  check:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test
